In [ ]:
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt


#Data Preprocessing

In [ ]:
dataset  =pd.read_csv("/content/50_Startups.csv")

In [ ]:
x= dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

##Encodeing

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


##spliting into train test set


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)


In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [ ]:


data = np.array([1.0, 0.0, 0.0, 91678.39, 135494565.07, 252645664.93])


In [ ]:
regressor.predict(data.reshape(1, -1))

array([-1649649.05607099])

In [ ]:
print(x_test,y_test)

[[1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [1.0 0.0 0.0 38558.51 82982.09 174999.3]
 [0.0 1.0 0.0 61994.48 115641.28 91131.24]
 [0.0 0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [1.0 0.0 0.0 64664.71 139553.16 137962.62]
 [1.0 0.0 0.0 63408.86 129219.61 46085.25]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]] [134307.35  81005.76  99937.59  64926.08 125370.37  35673.41 105733.54
 107404.34  97427.84 122776.86]


In [ ]:
y_pred = regressor.predict(x_test)

In [ ]:
for i in range(len(y_pred)):
  print(y_test[i],"  -  " ,  y_pred[i] ,"= " ,y_test[i]-y_pred[i])
  print()

134307.35   -   126362.8790825142 =  7944.4709174858

81005.76   -   84608.4538364177 =  -3602.693836417704

99937.59   -   99677.49425153545 =  260.0957484645478

64926.08   -   46357.46068579509 =  18568.61931420491

125370.37   -   128750.48288497524 =  -3380.112884975242

35673.41   -   50912.417419018544 =  -15239.00741901854

105733.54   -   109741.35032699727 =  -4007.810326997278

107404.34   -   100643.24281642918 =  6761.097183570819

97427.84   -   97599.2757459815 =  -171.43574598150735

122776.86   -   113097.42524435539 =  9679.434755644616



#useing backward elemination
